# Generated by Django 3.0.6 on 2020-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformdetails',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
