# Generated by Django 3.0.6 on 2020-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_userformdetails_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformdetails',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
