# Generated by Django 3.0.6 on 2020-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_auto_20200706_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformdetails',
            name='pdf_file',
            field=models.ImageField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
