# Generated by Django 3.0.6 on 2020-07-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0004_auto_20200706_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userformdetails',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='userformdetails',
            old_name='pdf_file',
            new_name='upload_pdf',
        ),
    ]
