# Generated by Django 3.0.6 on 2020-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_auto_20200706_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformdetails',
            name='upload_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
