# Generated by Django 3.0.6 on 2020-07-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_auto_20200706_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
